# Generated by Django 3.1.6 on 2021-10-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0008_figures_db_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figures_category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='figures_category',
            name='figure',
        ),
        migrations.RemoveField(
            model_name='figures_entries',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='figures_entries',
            name='figure',
        ),
        migrations.RemoveField(
            model_name='figures_releases',
            name='figure',
        ),
        migrations.RemoveField(
            model_name='pictures',
            name='figure',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='root',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Entries',
        ),
        migrations.DeleteModel(
            name='Figures_category',
        ),
        migrations.DeleteModel(
            name='Figures_db',
        ),
        migrations.DeleteModel(
            name='Figures_entries',
        ),
        migrations.DeleteModel(
            name='Figures_Releases',
        ),
        migrations.DeleteModel(
            name='Pictures',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
